version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 117hd-api:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/117HD-API/logs:/code/logs:rw
